const KEY='chronicle-state-v1';
const defaultState={onboarded:false,name:'El',goal:8,mix:{Bahamian:40,Caribbean:25,World:20,American:15},completed:{},attempts:{},reviews:[],xp:0,days:[],settings:{text:17,reduced:false,sound:false},tab:'today'};
let state=load(); let lessonSession=null;
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaultState}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function today(){return new Date().toISOString().slice(0,10)}
function completedCount(path){return LESSONS.filter(l=>l.path===path&&state.completed[l.id]).length}
function dueReviews(){let now=Date.now();return state.reviews.filter(r=>new Date(r.due).getTime()<=now)}
function chooseDaily(){const un=LESSONS.filter(l=>!state.completed[l.id]); if(!un.length)return LESSONS[new Date().getDate()%LESSONS.length]; const seed=[...today()].reduce((a,c)=>a+c.charCodeAt(0),0); const weighted=[]; Object.entries(state.mix).forEach(([p,w])=>{const list=un.filter(l=>l.path===p);for(let i=0;i<w;i++)if(list.length)weighted.push(list[i%list.length])}); return weighted[seed%weighted.length]||un[0]}
function shell(content,tab=state.tab){document.documentElement.style.setProperty('--text',state.settings.text+'px');document.body.classList.toggle('reduced',state.settings.reduced);document.getElementById('app').innerHTML=`<main class="app"><div class="topbar"><div class="brand"><div><div class="eyebrow">History you can remember</div><h1>Chronicle</h1></div><div class="pill">${state.xp} XP</div></div></div>${content}</main><nav class="bottom-nav"><div class="inner">${[['today','⌂','Today'],['paths','⌁','Paths'],['review','↻','Review'],['timeline','⌛','Timeline'],['profile','⚙','Profile']].map(([id,ic,tx])=>`<button class="nav-btn ${tab===id?'active':''}" onclick="go('${id}')"><span>${ic}</span>${tx}</button>`).join('')}</div></nav>`}
function go(tab){state.tab=tab;save();render()}
function render(){if(!state.onboarded)return onboarding(); ({today:renderToday,paths:renderPaths,review:renderReview,timeline:renderTimeline,profile:renderProfile}[state.tab]||renderToday)()}
function onboarding(){let step=0,selected=['Bahamian','Caribbean']; const draw=()=>{const pages=[`<div class="eyebrow">A private, free learning app</div><h1>History should feel like a story, not homework.</h1><p class="muted">Daily cinematic lessons, retrieval practice, and spaced review in under ten minutes.</p><button class="button block" id="next">Begin</button>`,`<div class="eyebrow">Choose your focus</div><h1>Which histories pull you in?</h1><div class="choice-grid">${['Bahamian','Caribbean','World','American'].map(x=>`<button class="choice ${selected.includes(x)?'selected':''}" data-choice="${x}">${x} History</button>`).join('')}</div><button class="button block" id="next">Continue</button>`,`<div class="eyebrow">Daily rhythm</div><h1>How much time fits real life?</h1><div class="choice-grid">${[5,8,10].map(x=>`<button class="choice ${state.goal===x?'selected':''}" data-goal="${x}">${x} minutes</button>`).join('')}</div><button class="button block" id="next">Start learning</button>`];document.getElementById('app').innerHTML=`<section class="onboarding">${pages[step]}</section>`;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const x=b.dataset.choice;selected=selected.includes(x)?selected.filter(v=>v!==x):[...selected,x];draw()});document.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{state.goal=+b.dataset.goal;draw()});document.getElementById('next').onclick=()=>{if(step<2){step++;draw()}else{state.onboarded=true;state.days=[today()];save();render()}}};draw()}
function renderToday(){const l=chooseDaily(),due=dueReviews().length,week=state.days.filter(d=>(Date.now()-new Date(d).getTime())<7*864e5).length;shell(`<section><p class="muted">Welcome back, ${esc(state.name)}.</p><h2 class="section-title">Today’s ${state.goal}-minute journey</h2><article class="card hero"><div class="eyebrow">${l.path} · ${l.era}</div><h2>${l.title}</h2><p>${l.beats[0][1]}</p><button class="button" onclick="startLesson('${l.id}')">Start lesson</button></article><div class="stats"><div class="stat"><span class="muted">Learning rhythm</span><strong>${state.days.length}</strong><small>active days</small></div><div class="stat"><span class="muted">This week</span><strong>${week*state.goal}</strong><small>minutes</small></div><div class="stat"><span class="muted">Due now</span><strong>${due}</strong><small>reviews</small></div></div><article class="card"><div class="eyebrow">One thing to remember</div><p><strong>${l.beats[4][1]}</strong></p></article></section>`)}
function renderPaths(){const paths=['Bahamian','Caribbean','World','American'];shell(`<h2 class="section-title">Learning paths</h2><p class="muted">Bahamian history leads your default mix. Every path remains open.</p><div class="path-grid">${paths.map(p=>{const n=completedCount(p),total=LESSONS.filter(l=>l.path===p).length;return `<article class="card path-card"><div class="eyebrow">${p==='Bahamian'?'Priority path':'History path'}</div><h3>${p}</h3><div class="progress"><span style="width:${n/total*100}%"></span></div><p class="muted">${n} of ${total} complete</p></article>`}).join('')}</div>${paths.map(p=>`<h2 class="section-title">${p}</h2><div class="lesson-list">${LESSONS.filter(l=>l.path===p).map((l,i)=>`<div class="lesson-row"><div class="node">${state.completed[l.id]?'✓':i+1}</div><div><strong>${l.title}</strong><div class="muted">${l.era} · ${l.minutes} min</div></div><button class="button secondary" onclick="startLesson('${l.id}')">${state.completed[l.id]?'Replay':'Open'}</button></div>`).join('')}</div>`).join('')}`,'paths')}
function startLesson(id){const lesson=LESSONS.find(l=>l.id===id);lessonSession={lesson,index:0,phase:'beats',score:0,q:0,answered:false};drawLesson()}
function drawLesson(){const s=lessonSession,l=s.lesson;if(s.phase==='beats'){const b=l.beats[s.index];document.getElementById('app').innerHTML=`<main class="app"><section class="card story"><div class="eyebrow">${l.path} · ${s.index+1}/${l.beats.length}</div><h2>${b[0]}</h2><p>${b[1]}</p><div class="progress"><span style="width:${(s.index+1)/l.beats.length*100}%"></span></div><div class="story-nav"><button class="button secondary" onclick="lessonBack()">${s.index?'Back':'Exit'}</button><button class="button" onclick="lessonNext()">${s.index===l.beats.length-1?'Quiz':'Continue'}</button></div></section></main>`}else if(s.phase==='quiz')drawQuiz();else drawFinish()}
function lessonBack(){if(lessonSession.index===0){render()}else{lessonSession.index--;drawLesson()}}
function lessonNext(){if(lessonSession.index<lessonSession.lesson.beats.length-1){lessonSession.index++;drawLesson()}else{lessonSession.phase='quiz';drawLesson()}}
function drawQuiz(){const s=lessonSession,q=s.lesson.quiz[s.q];document.getElementById('app').innerHTML=`<main class="app"><section class="card story"><div class="eyebrow">Retrieval ${s.q+1}/${s.lesson.quiz.length}</div><h2>${q.q}</h2><div>${q.o.map((x,i)=>`<button class="quiz-option" onclick="answerQuiz(${i})">${x}</button>`).join('')}</div><div id="feedback"></div></section></main>`}
function answerQuiz(i){const s=lessonSession,q=s.lesson.quiz[s.q];if(s.answered)return;s.answered=true;document.querySelectorAll('.quiz-option').forEach((b,j)=>{if(j===q.a)b.classList.add('correct');else if(j===i)b.classList.add('wrong');b.disabled=true});if(i===q.a)s.score++;document.getElementById('feedback').innerHTML=`<div class="feedback"><strong>${i===q.a?'Correct':'Not quite'}</strong><p>${q.e}</p><button class="button block" onclick="nextQuiz()">Continue</button></div>`}
function nextQuiz(){const s=lessonSession;s.answered=false;if(s.q<s.lesson.quiz.length-1){s.q++;drawQuiz()}else{s.phase='finish';drawFinish()}}
function drawFinish(){const s=lessonSession,l=s.lesson,pct=Math.round(s.score/l.quiz.length*100);document.getElementById('app').innerHTML=`<main class="app"><section class="card story"><div class="eyebrow">Lesson complete</div><h2>Tell the story back.</h2><p>In 30 seconds, explain: <strong>what happened, why it happened, and why it mattered.</strong></p><div class="stats"><div class="stat"><span class="muted">Score</span><strong>${pct}%</strong></div><div class="stat"><span class="muted">Status</span><strong>${l.status}</strong></div><div class="stat"><span class="muted">Source note</span><small>${l.source}</small></div></div><label class="form-row">How confident are you?<select id="confidence"><option value="1">Low</option><option value="2" selected>Medium</option><option value="3">High</option></select></label><button class="button block" onclick="completeLesson()">Save and schedule review</button></section></main>`}
function completeLesson(){const s=lessonSession,l=s.lesson,conf=+document.getElementById('confidence').value,ratio=s.score/l.quiz.length;state.completed[l.id]={date:today(),score:s.score,total:l.quiz.length};state.xp+=10+s.score*5;if(!state.days.includes(today()))state.days.push(today());const base=ratio===1&&conf===3?3:ratio>=.67?1:0;const intervals=[1,3,7,14,30,90],idx=Math.min(base,intervals.length-1);const due=new Date(Date.now()+intervals[idx]*864e5).toISOString();state.reviews=state.reviews.filter(r=>r.lessonId!==l.id);state.reviews.push({lessonId:l.id,due,stage:idx});save();lessonSession=null;state.tab='today';render()}
function renderReview(){const due=dueReviews();shell(`<h2 class="section-title">Review</h2><p class="muted">Answers stay hidden until you attempt retrieval.</p>${due.length?due.map(r=>{const l=LESSONS.find(x=>x.id===r.lessonId);return `<article class="card"><div class="eyebrow">Due now · stage ${r.stage+1}</div><h3>${l.title}</h3><p>${l.beats[4][1]}</p><button class="button" onclick="startReview('${l.id}')">Review</button></article>`}).join(''):`<div class="card empty"><h3>No reviews due.</h3><p class="muted">Complete a lesson. Chronicle will bring it back when recall needs strengthening.</p></div>`}`,'review')}
function startReview(id){startLesson(id)}
function renderTimeline(){const sorted=[...LESSONS].sort((a,b)=>a.order-b.order||a.path.localeCompare(b.path));shell(`<h2 class="section-title">Connected timeline</h2><p class="muted">Compare regions instead of learning each history in isolation.</p>${sorted.map((l,i)=>`<div class="timeline-item"><div class="eyebrow">${l.era} · ${l.path}</div><strong>${l.title}</strong><p class="muted">${l.beats[5][1]}</p>${i%4===3?`<div class="pill">Meanwhile: other regions were changing too</div>`:''}</div>`).join('')}`,'timeline')}
function renderProfile(){shell(`<h2 class="section-title">Profile and settings</h2><article class="card"><label class="form-row">Name<input value="${esc(state.name)}" onchange="state.name=this.value;save()"></label><label class="form-row">Daily goal<select onchange="state.goal=+this.value;save()">${[5,8,10].map(x=>`<option ${state.goal===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="form-row">Text size<input type="range" min="15" max="22" value="${state.settings.text}" oninput="state.settings.text=+this.value;save();render()"></label><label><input type="checkbox" ${state.settings.reduced?'checked':''} onchange="state.settings.reduced=this.checked;save()"> Reduced motion</label></article><article class="card"><div class="eyebrow">Data</div><p class="muted">Free, local-first, no ads, no account, no selling data.</p><button class="button secondary" onclick="exportData()">Export progress</button> <button class="button secondary" onclick="document.getElementById('import').click()">Import</button><input id="import" type="file" hidden accept="application/json" onchange="importData(this.files[0])"><button class="button secondary" onclick="resetData()">Reset</button></article><article class="card"><div class="eyebrow">Learning method</div><p>Chronicle uses retrieval practice, spacing, interleaving, dual coding, generation, explanatory feedback, and teach-back. Historical interpretations can change. Source notes identify where deeper study should begin.</p></article>`,'profile')}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='chronicle-progress.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{state={...defaultState,...JSON.parse(r.result)};save();render()}catch{alert('That file is not valid Chronicle progress.')}};r.readAsText(file)}
function resetData(){if(confirm('Erase all Chronicle progress on this device?')){localStorage.removeItem(KEY);state={...defaultState};render()}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
